package observador;

import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Observable;
import java.util.Observer;
import javax.imageio.ImageIO;
import javax.swing.JPanel;
import observable.Temperatura;
/**
 *
 * @author pablorobles
 */
public class TiempoSatelital extends JPanel implements Observer {
    
    // Se usa un array de observables para que el numero de temperaturas del mapa 
    // pueda variar
    protected ArrayList <Temperatura> listaObservables;
    protected double[] listaTemperaturas;
    
    private Image fondo;
    /**
     * Creates new form TiempoSatelital
     */
    public TiempoSatelital(ArrayList <Temperatura> temperaturas) throws IOException {
        listaObservables = temperaturas;
        listaTemperaturas = new double[temperaturas.size()];
        Arrays.fill(listaTemperaturas, 0);
        
        //Para poner de fondo la imagen del mapa
        URL url = this.getClass().getResource("../imagenes/mapa_espana.jpg");
        fondo = ImageIO.read(new File(url.getPath()));
        initComponents();
    }
    
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        g.drawImage(fondo, 0, 0, this);
    }
    
    @Override
    public void update(Observable o, Object arg) {
        
        for (int i = 0; i < listaObservables.size(); i++) {
            listaTemperaturas[i] = this.listaObservables.get(i).getTemperatura();
        }

        this.etiqueta_GR.setText("Granada: "+(double) this.listaObservables.get(0).getTemperatura()+"ºC");
        this.etiqueta_BILB.setText("Bilbao: "+(double) this.listaObservables.get(1).getTemperatura()+"ºC");
        this.etiqueta_MAD.setText("Madrid: "+(double) this.listaObservables.get(2).getTemperatura()+"ºC");
        this.etiqueta_BCN.setText("Barcelona: "+(double) this.listaObservables.get(3).getTemperatura()+"ºC");
        this.etiqueta_SEV.setText("Sevilla: "+(double) this.listaObservables.get(4).getTemperatura()+"ºC");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiqueta_GR = new javax.swing.JLabel();
        etiqueta_BILB = new javax.swing.JLabel();
        etiqueta_MAD = new javax.swing.JLabel();
        etiqueta_SEV = new javax.swing.JLabel();
        etiqueta_BCN = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(854, 640));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etiqueta_GR.setBackground(new java.awt.Color(255, 255, 255));
        etiqueta_GR.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        etiqueta_GR.setText("Granada: --.--ºC");
        etiqueta_GR.setOpaque(true);
        add(etiqueta_GR, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, -1, -1));

        etiqueta_BILB.setBackground(new java.awt.Color(255, 255, 255));
        etiqueta_BILB.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        etiqueta_BILB.setText("Bilbao: --.--ºC");
        etiqueta_BILB.setOpaque(true);
        add(etiqueta_BILB, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        etiqueta_MAD.setBackground(new java.awt.Color(255, 255, 255));
        etiqueta_MAD.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        etiqueta_MAD.setText("Madrid: --.--ºC");
        etiqueta_MAD.setOpaque(true);
        add(etiqueta_MAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, -1, -1));

        etiqueta_SEV.setBackground(new java.awt.Color(255, 255, 255));
        etiqueta_SEV.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        etiqueta_SEV.setText("Sevilla: --.--ºC");
        etiqueta_SEV.setOpaque(true);
        add(etiqueta_SEV, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 470, -1, -1));

        etiqueta_BCN.setBackground(new java.awt.Color(255, 255, 255));
        etiqueta_BCN.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        etiqueta_BCN.setText("Barcelona: --.--ºC");
        etiqueta_BCN.setOpaque(true);
        add(etiqueta_BCN, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiqueta_BCN;
    private javax.swing.JLabel etiqueta_BILB;
    private javax.swing.JLabel etiqueta_GR;
    private javax.swing.JLabel etiqueta_MAD;
    private javax.swing.JLabel etiqueta_SEV;
    // End of variables declaration//GEN-END:variables
}
