package GUI;

import java.util.Observable;

/**
 *
 * @author pablorobles
 */
public class CuentaRevoluciones extends ObservadorMotor {

    
    public CuentaRevoluciones() {
        initComponents();
    }

    
    @Override
    public void update(Observable o, Object arg) {        
        etiqueta_rpm.setText( String.format("%d", miObservable.getRPM()) );
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_RPM = new javax.swing.JPanel();
        etiqueta_rpm = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Cuentarrevoluciones"));
        setLayout(new java.awt.BorderLayout());

        panel_RPM.setBorder(javax.swing.BorderFactory.createTitledBorder("RPM"));
        panel_RPM.setLayout(new java.awt.BorderLayout());

        etiqueta_rpm.setText("00.00");
        panel_RPM.add(etiqueta_rpm, java.awt.BorderLayout.CENTER);

        add(panel_RPM, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiqueta_rpm;
    private javax.swing.JPanel panel_RPM;
    // End of variables declaration//GEN-END:variables
}
