package GUI.MonitorMecanico;

import GUI.ObservadorMotor;
import controlVelocidad.EstadoMotor;
import java.awt.Color;
import java.util.Observable;

/**
 *
 * @author alex
 */
public class Combustible extends ObservadorMotor {
    protected boolean motorParado;

    /**
     * Creates new form Combustible
     */
    public Combustible() {
        initComponents();
        boton.setEnabled(false);
    }
    
    @Override
    public void update(Observable o, Object arg) {
        textoVar.setText( ""+miObservable.getConsumo() );
        combustibleBarra.setValue((int) miObservable.getCombustible());
        combustibleBarra.setString(miObservable.getCombustible() + " litros");
        setColorBarra();
        
        motorParado = (miObservable.getEstadoMotor()==EstadoMotor.APAGADO) && (miObservable.getRPM() == 0);
        if (miObservable.getCombustible() < 10) {
            if (motorParado)
                boton.setEnabled(true);
            else
                boton.setEnabled(false);
        }
    }
    
    
    void setColorBarra() {
        double perc = combustibleBarra.getPercentComplete();
        int green = (int) (255*perc);           // 100% verde
        int red = (int) (255 - (255*perc));     // 100% rojo
        
        combustibleBarra.setForeground(
                Color.getHSBColor(
                        Color.RGBtoHSB(red, green, 0, null)[0], 
                        Color.RGBtoHSB(red, green, 0, null)[1], 
                        Color.RGBtoHSB(red, green, 0, null)[2])
        );
    }
    
    
    void resetBoton () {
        boton.setEnabled(false);
    }
    
    void ocultarBarra() {
        combustibleBarra.setVisible(false);
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textFijo = new javax.swing.JLabel();
        textoVar = new javax.swing.JLabel();
        textUnidad = new javax.swing.JLabel();
        combustibleBarra = new javax.swing.JProgressBar();
        boton = new javax.swing.JButton();

        textFijo.setText("Consumo: ");
        add(textFijo);

        textoVar.setText("00.00");
        add(textoVar);

        textUnidad.setText("l/100Km");
        add(textUnidad);

        combustibleBarra.setMaximum(75);
        combustibleBarra.setToolTipText("");
        combustibleBarra.setStringPainted(true);
        add(combustibleBarra);

        boton.setText("Respostar");
        boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonActionPerformed(evt);
            }
        });
        add(boton);
    }// </editor-fold>//GEN-END:initComponents

    private void botonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonActionPerformed
        miObservable.repostar();
        resetBoton();
    }//GEN-LAST:event_botonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton;
    private javax.swing.JProgressBar combustibleBarra;
    private javax.swing.JLabel textFijo;
    private javax.swing.JLabel textUnidad;
    private javax.swing.JLabel textoVar;
    // End of variables declaration//GEN-END:variables
}
