package GUI.MonitorMecanico;

import java.util.Observable;

/**
 *
 * @author alex
 */
public class CombustibleSteelSeries extends Combustible {

    /**
     * Creates new form Combustible
     */
    public CombustibleSteelSeries() {
        super();
        initComponents();
        ocultarBarra();
    }
    
    @Override
    public void update(Observable o, Object arg) {
        super.update(o, arg);
        radial1Square1.setValue(miObservable.getCombustible());
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radial1Square1 = new eu.hansolo.steelseries.gauges.Radial1Square();

        radial1Square1.setMaxValue(80.0);
        radial1Square1.setMaximumSize(new java.awt.Dimension(100, 100));
        radial1Square1.setMinMeasuredValueVisible(true);
        radial1Square1.setTickLabelPeriod(10);
        radial1Square1.setTitle("Combustible");
        radial1Square1.setUnitString("litros");
        add(radial1Square1);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private eu.hansolo.steelseries.gauges.Radial1Square radial1Square1;
    // End of variables declaration//GEN-END:variables
}
