package GUI.MonitorMecanico;

import GUI.ObservadorMotor;
import controlVelocidad.EstadoMotor;
import java.awt.Color;
import java.util.Observable;

/**
 *
 * @author alex
 */
public class ControlFrenos extends ObservadorMotor {
    private boolean motorParado;

    /**
     * Creates new form AtributoMecanica
     */
    public ControlFrenos() {
        initComponents();
        
        boton.setEnabled(false);
        textoFijo.setText("Estado frenos: ");
    } 
    
    @Override
    public void update(Observable o, Object arg) {
        setTextoRevisar(miObservable.necesitaCambiarFrenos());
        motorParado = (miObservable.getEstadoMotor()==EstadoMotor.APAGADO) && (miObservable.getRPM() == 0);
    }
    
    public void setTextoRevisar(boolean revision) {
        if (!revision) {
            textoVar.setText("Correcto");
            textoVar.setForeground(Color.GREEN);
            boton.setEnabled(false);
        }
        else {
            textoVar.setText("Revisar");
            textoVar.setForeground(Color.RED);
            if (motorParado)
                boton.setEnabled(true);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textoFijo = new javax.swing.JLabel();
        textoVar = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        boton = new javax.swing.JButton();

        setLayout(new java.awt.GridLayout(1, 3));

        textoFijo.setText("Estado:");
        add(textoFijo);

        textoVar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textoVar.setText("Correcto | Revisar");
        textoVar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add(textoVar);

        separador.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(separador);

        boton.setText("Corregir");
        boton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonOnClick(evt);
            }
        });
        add(boton);
    }// </editor-fold>//GEN-END:initComponents

    private void botonOnClick(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOnClick
        miObservable.cambiarFrenos();
    }//GEN-LAST:event_botonOnClick


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton;
    private javax.swing.JSeparator separador;
    private javax.swing.JLabel textoFijo;
    private javax.swing.JLabel textoVar;
    // End of variables declaration//GEN-END:variables

}
