/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.MonitorMecanico;

/**
 *
 * @author alex
 */
public class Test extends AbstractControl {

    /**
     * Creates new form Test
     */
    public Test() {
        super();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        abstractControl1 = new GUI.MonitorMecanico.AbstractControl();

        setLayout(new java.awt.BorderLayout());
        add(abstractControl1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private GUI.MonitorMecanico.AbstractControl abstractControl1;
    // End of variables declaration//GEN-END:variables
}
