
USE DS;

DROP TABLE IF EXISTS Valoraciones;
DROP TABLE IF EXISTS Valorables;
DROP TABLE IF EXISTS Admins;
DROP TABLE IF EXISTS Superadmins;
DROP TABLE IF EXISTS Entidades;
DROP TABLE IF EXISTS Usuarios;

