package GUI;

import controlAutomatico.ControlAutomatico;
import controlVelocidad.Filtros.FiltroCalcularRPM;
import controlVelocidad.Filtros.FiltroRozamiento;
import controlVelocidad.Cliente;
import controlVelocidad.GestorFiltros;
import controlVelocidad.Objetivo;

/**
 *
 * @author alex
 */
public class VentanaPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        
        Objetivo motor = new Objetivo();
        GestorFiltros gestor = new GestorFiltros(motor);
        Cliente controlador = new Cliente(gestor);
        
        /****/
        
        FiltroCalcularRPM filtro_velocidad = new FiltroCalcularRPM();
        FiltroRozamiento filtro_rozamiento = new FiltroRozamiento();
        gestor.setFiltro(filtro_velocidad);
        gestor.setFiltro(filtro_rozamiento);
        
        /****/

        salpicadero.setObjetivo(motor);        
        controles.setControlador(controlador);
        monitorMecanico.setObjetivo(motor);
        salpicaderoSteelSeries.setObjetivo(motor);
        monitorMecanicoSteelSeries.setObjetivo(motor);
        
        /****/

        ControlAutomatico scav = ControlAutomatico.getInstancia(controles);
        scav.setObservable(motor);
        controlesSCAV.setObservable(scav);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabsPanel = new javax.swing.JTabbedPane();
        swingPanel = new javax.swing.JPanel();
        salpicadero = new GUI.Salpicadero();
        monitorMecanico = new GUI.MonitorMecanico.MonitorMecanico();
        SteelSeriesPanel = new javax.swing.JPanel();
        salpicaderoSteelSeries = new GUI.SalpicaderoSteelSeries();
        monitorMecanicoSteelSeries = new GUI.MonitorMecanico.MonitorMecanicoSteelSeries();
        controles = new GUI.Controles();
        controlesSCAV = new GUI.SCAV.ControlesSCAV();

        setPreferredSize(new java.awt.Dimension(1024, 768));
        setLayout(new java.awt.BorderLayout());

        swingPanel.setPreferredSize(new java.awt.Dimension(1024, 768));
        swingPanel.setLayout(new java.awt.GridLayout());
        swingPanel.add(salpicadero);
        swingPanel.add(monitorMecanico);

        tabsPanel.addTab("Swing", null, swingPanel, "Interfaz con componentes Swing");
        swingPanel.getAccessibleContext().setAccessibleName("");

        SteelSeriesPanel.setLayout(new java.awt.GridLayout(1, 0));
        SteelSeriesPanel.add(salpicaderoSteelSeries);
        SteelSeriesPanel.add(monitorMecanicoSteelSeries);

        tabsPanel.addTab("SteelSeries", SteelSeriesPanel);

        add(tabsPanel, java.awt.BorderLayout.CENTER);
        add(controles, java.awt.BorderLayout.PAGE_START);
        add(controlesSCAV, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel SteelSeriesPanel;
    private GUI.Controles controles;
    private GUI.SCAV.ControlesSCAV controlesSCAV;
    private GUI.MonitorMecanico.MonitorMecanico monitorMecanico;
    private GUI.MonitorMecanico.MonitorMecanicoSteelSeries monitorMecanicoSteelSeries;
    private GUI.Salpicadero salpicadero;
    private GUI.SalpicaderoSteelSeries salpicaderoSteelSeries;
    private javax.swing.JPanel swingPanel;
    private javax.swing.JTabbedPane tabsPanel;
    // End of variables declaration//GEN-END:variables
}
